# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-08-06 15:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import newsletter.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=30, validators=[newsletter.validators.validate_char, newsletter.validators.validate_len], verbose_name='Nome')),
                ('lastname', models.CharField(max_length=30, validators=[newsletter.validators.validate_char, newsletter.validators.validate_len], verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('reason', models.CharField(blank=True, choices=[('Motivo 01', 'Motivo 01'), ('Motivo 02', 'Motivo 02'), ('Motivo 03', 'Motivo 03')], max_length=20, null=True, verbose_name='Motivo da Inscrição')),
            ],
            options={
                'verbose_name': 'Inscrito',
                'verbose_name_plural': 'Inscritos',
            },
        ),
    ]
