# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-24 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import newsletter.validators


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('text', models.TextField(verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='lastname',
            field=models.CharField(max_length=30, validators=[newsletter.validators.validate_char, newsletter.validators.validate_len], verbose_name='Sobrenome(s)'),
        ),
    ]
