# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-24 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0002_auto_20211124_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub-Titulo'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_br',
            field=models.TextField(null=True, verbose_name='Texto'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Texto'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_es',
            field=models.TextField(null=True, verbose_name='Texto'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_fr',
            field=models.TextField(null=True, verbose_name='Texto'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_pt_br',
            field=models.TextField(null=True, verbose_name='Texto'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Titulo'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Titulo'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Titulo'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Titulo'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_pt_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Titulo'),
        ),
    ]
