# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-08-02 16:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import letter.validators


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0002_auto_20210730_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'Inscrito', 'verbose_name_plural': 'Inscritos'},
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='lastname',
            field=models.CharField(max_length=30, validators=[letter.validators.validate_char, letter.validators.validate_len], verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='name',
            field=models.CharField(max_length=30, validators=[letter.validators.validate_char, letter.validators.validate_len], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='reason',
            field=models.CharField(blank=True, choices=[('Motivo 01', 'Motivo 01'), ('Motivo 02', 'Motivo 02'), ('Motivo 03', 'Motivo 03')], max_length=20, null=True, verbose_name='Motivo da Inscrição'),
        ),
    ]
