# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-24 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0003_auto_20211124_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='sub_title_br',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub-Titulo'),
        ),
        migrations.AddField(
            model_name='news',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub-Titulo'),
        ),
        migrations.AddField(
            model_name='news',
            name='sub_title_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub-Titulo'),
        ),
        migrations.AddField(
            model_name='news',
            name='sub_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub-Titulo'),
        ),
        migrations.AddField(
            model_name='news',
            name='sub_title_pt_br',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub-Titulo'),
        ),
    ]
