# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-24 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0004_auto_20211124_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='sub_title_br',
        ),
        migrations.RemoveField(
            model_name='news',
            name='sub_title_fr',
        ),
        migrations.RemoveField(
            model_name='news',
            name='text_br',
        ),
        migrations.RemoveField(
            model_name='news',
            name='text_fr',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_br',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_fr',
        ),
    ]
