# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-24 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0005_auto_20211124_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoria'),
        ),
    ]
