# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-08-06 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='staff',
            new_name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='admin',
        ),
    ]
