# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-08-24 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210806_1329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdressModel',
            new_name='AddressModel',
        ),
        migrations.RenameField(
            model_name='addressmodel',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Sobrenome(s)'),
        ),
    ]
