# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-24 14:41
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import newsletter.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210824_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicprofilemodel',
            options={'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuário'},
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.BasicProfileModel', verbose_name='Perfil Usuário'),
        ),
        migrations.AlterField(
            model_name='basicprofilemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='email',
            field=models.EmailField(max_length=200, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='first_name',
            field=models.CharField(max_length=100, validators=[newsletter.validators.validate_char, newsletter.validators.validate_len], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='last_name',
            field=models.CharField(max_length=200, validators=[newsletter.validators.validate_char, newsletter.validators.validate_len], verbose_name='Sobrenome(s)'),
        ),
        migrations.AlterField(
            model_name='socialnetworkmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.BasicProfileModel', verbose_name='Perfil Usuário'),
        ),
    ]
